import { IJob, DamageType, IAbility, IAbilitySetting, Role, AbilityType, IStance, byName, byBuffApply, byBuffRemove } from "../Models"
import { settings, IAbilities, abilitySortFn, getAbilitiesFrom, healerSharedAbilities, medicine } from "./shared"

export const SCH: IJob = {
  name: "SCH",
  role: Role.Healer,
  pets: [
    { name: "Selene", icon: ("62_PetsFairy/0806_Embrace") },
    { name: "Eos", icon: ("62_PetsFairy/0802_Embrace") }
  ],
  defaultPet: "Selene",
  icon: ("JobIcons/Scholar_Icon_10"),
  abilities: [
    {
      name: "Chain Stratagem",
      duration: 15,
      cooldown: 120,
      xivDbId: "7436",
      requiresBossTarget: true,
      icon: ("62_PetsFairy/7436_Chain Stratagem"),
      abilityType: AbilityType.PartyDamageBuff,
    },
    {
      name: "Shadow Flare",
      duration: 15,
      cooldown: 60,
      xivDbId: "179",
      icon: ("52_Summoner/0179_Shadow Flare"),
      abilityType: AbilityType.Damage,
    },
    {
      name: "Rouse",
      duration: 20,
      cooldown: 60,
      xivDbId: "176",
      icon: ("52_Summoner/0176_Rouse"),
      abilityType: AbilityType.SelfDamageBuff | AbilityType.HealingBuff,
    },
    {
      name: "Sacred Soil",
      duration: 15,
      cooldown: 30,
      xivDbId: "188",
      icon: ("62_PetsFairy/0188_Sacred Soil"),
      abilityType: AbilityType.SelfDefense | AbilityType.PartyDefense,
    },
    {
      name: "Indomitability",
      duration: 0,
      cooldown: 30,
      xivDbId: "3583",
      icon: ("62_PetsFairy/3583_Indomitability"),
      abilityType: AbilityType.Healing,
    },
    {
      name: "Dissipation",
      duration: 30,
      cooldown: 180,
      xivDbId: "3587",
      icon: ("62_PetsFairy/3587_Dissipation"),
      abilityType: AbilityType.Healing,
    },
    {
      name: "Excogitation",
      duration: 0,
      cooldown: 45,
      xivDbId: "7434",
      requiresBossTarget: true,
      icon: ("62_PetsFairy/7434_Excogitation"),
      abilityType: AbilityType.Healing,
      settings: [settings.target],
    },
    {
      name: "Lustrate",
      duration: 0,
      cooldown: 1,
      xivDbId: "0189",
      icon: ("62_PetsFairy/0189_Lustrate"),
      abilityType: AbilityType.Healing,
      settings: [settings.target],
    },
    {
      name: "Aetherflow",
      duration: 0,
      cooldown: 60,
      icon: ("62_PetsFairy/8908_Aetherflow"),
      xivDbId: "166",
      abilityType: AbilityType.Utility,
    },
    {
      name: "Deployment Tactics",
      duration: 0,
      cooldown: 120,
      xivDbId: "3585",
      icon: ("62_PetsFairy/3585_Deployment Tactics"),
      abilityType: AbilityType.Utility,
    },
    {
      name: "Whispering Dawn",
      duration: 21,
      cooldown: 60,
      xivDbId: "803",
      icon: ("62_PetsFairy/0803_Whispering Dawn"),
      pet: "Eos",
      abilityType: AbilityType.Pet,
    },
    {
      name: "Fey Covenant",
      duration: 20,
      cooldown: 120,
      xivDbId: "804",
      icon: ("62_PetsFairy/0804_Fey Covenant"),
      pet: "Eos",
      abilityType: AbilityType.Pet,
    },
    {
      name: "Fey Illumination",
      duration: 20,
      cooldown: 120,
      xivDbId: "805",
      icon: ("62_PetsFairy/0805_Fey Illumination"),
      pet: "Eos",
      abilityType: AbilityType.Pet,
    },
    {
      name: "Silent Dusk",
      duration: 0,
      cooldown: 40,
      xivDbId: "807",
      requiresBossTarget: true,
      icon: ("62_PetsFairy/0807_Silent Dusk"),
      pet: "Selene",
      abilityType: AbilityType.Pet,
    },
    {
      name: "Fey Caress",
      duration: 0,
      cooldown: 60,
      xivDbId: "810",
      icon: ("62_PetsFairy/0810_Fey Caress"),
      pet: "Selene",
      abilityType: AbilityType.Pet,
    },
    {
      name: "Fey Wind",
      duration: 30,
      cooldown: 60,
      xivDbId: "811",
      icon: ("62_PetsFairy/0811_Fey Wind"),
      pet: "Selene",
      abilityType: AbilityType.Pet,
    },
    ...getAbilitiesFrom(healerSharedAbilities),
    medicine["Mind"]
  ].sort(abilitySortFn)
};


