name: Archive

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: create directory
      run: |
        mkdir art
    - name: archive      
      run: |
        zip -r ./art/archive.zip ./FightTimeLine/ClientApp
    - name: send to ftp
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_SERVER: ftp-eu.site4now.net
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./art
